### ISSUE TITLE
Cannot install lstchain due to numba aot error

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/cta-lstchain#1023]
Running `pip install -e .` gives me this error:

```
$ pip install -e .
Obtaining file:///fefs/home/maximilian.linhoff/cta-lstchain
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/fefs/aswg/workspace/maximilian.linhoff/.conda/envs/lst/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/fefs/aswg/workspace/maximilian.linhoff/.conda/envs/lst/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/fefs/aswg/workspace/maximilian.linhoff/.conda/envs/lst/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-41sj0a4i/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 446, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-41sj0a4i/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-41sj0a4i/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-41sj0a4i/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/fefs/home/maximilian.linhoff/cta-lstchain/./lstchain/reco/reconstructorCC.py", line 23, in <module>
          cc = CC('log_pdf_CC')
        File "/tmp/pip-build-env-41sj0a4i/overlay/lib/python3.8/site-packages/numba/pycc/cc.py", line 65, in __init__
          self._toolchain = Toolchain()
        File "/tmp/pip-build-env-41sj0a4i/overlay/lib/python3.8/site-packages/numba/pycc/platform.py", line 78, in __init__
          self._raise_external_compiler_error()
        File "/tmp/pip-build-env-41sj0a4i/overlay/lib/python3.8/site-packages/numba/pycc/platform.py", line 121, in _raise_external_compiler_error
          raise RuntimeError(msg)
      RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. If using conda try:
      
      #> conda install gcc_linux-64 gxx_linux-64
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

```

**Comment by morcuended** [comment]
If I remember correctly, this was only happening when trying to install it in the container, but not in my local machine.

**Comment by maxnoe** [comment]
We removed the aot compilation
