### ISSUE TITLE
Problem with argument parser

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#1046]
It seems there is a problem in v0.9.10 with command-line arguments after #1042 

```python
$ onsite_create_drs4_pedestal_file --run_number 9226
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/osa-v0.9.6/bin/onsite_create_drs4_pedestal_file", line 8, in <module>
    sys.exit(main())
  File "/fefs/aswg/software/conda/envs/osa-v0.9.6/lib/python3.8/site-packages/lstchain/scripts/onsite/onsite_create_drs4_pedestal_file.py", line 57, in main
    run = args.run_number
AttributeError: 'tuple' object has no attribute 'run_number'
```

I think it is this change:
```python
    args, remaining_args = parser.parse_known_args()
```

I realized just now because usually DRS4 runs are not processed by osa using v0.9.6

**Comment by maxnoe** [comment]
>     args, remaining_args = parser.parse_known_args()

It is rather that this change was only done half in the drs4 script.... sorry
