### ISSUE TITLE
Use correction for aberration in source-dependent analysis

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#1048]
https://github.com/cta-observatory/cta-lstchain/blob/3c75e08cbf5035f701408562f97e217880abe62d/lstchain/reco/dl1_to_dl2.py#L355-L356

Hi @SeiyaNozaki, above we are using the nominal focal length of 28 m (this is what is inside the files, as far as I know) for the source-dependent analysis. There could be some (marginal) gain if we use a correction for aberration (sharper Alpha distributions and perhaps a bit better performance of gammaness). Most likely this would be visible only at high energies, where the small difference may be significant considering the "sharpness" of the alpha distributions.

**Comment by SeiyaNozaki** [comment]
Following the suggestion, now I want to create `OpticsDescription` in case that subarray table is not readable (because of difference of ctapipe version). 

But I got the following error... Am I doing wrongly or is this ctapipe bug...?
https://github.com/cta-observatory/ctapipe/blob/main/ctapipe/instrument/optics.py#L199-L207
```
>>> from ctapipe.instrument import OpticsDescription
>>> 
>>> OpticsDescription.from_name("LST")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.0/lib/python3.10/site-packages/ctapipe/instrument/optics.py", line 207, in from_name
    raise ValueError(f"Unsupported version of optics table: {version}")
ValueError: Unsupported version of optics table: None
>>> 
>>> from ctapipe.utils import get_table_dataset
>>> table = get_table_dataset("optics", role="OpticsDescription.from_name")
>>> table
<Table length=9>
tel_description tel_type tel_subtype  mirror_area  mirror_type num_mirror_tiles equivalent_focal_length
                                           m2                                              m           
     str14        str5      str10       float64        str2         int64               float64        
--------------- -------- ----------- ------------- ----------- ---------------- -----------------------
        MST-SCT      MST         SCT 73.3475723267          SC                2           5.58629989624
        SST-GCT      SST         GCT 12.5663709641          SC                2           2.28299999237
            LST      LST          --  386.73324585          DC              198                    28.0
          MAGIC    MAGIC          --         239.0          DC              964                   16.97
      SST-ASTRI      SST       ASTRI 14.5625667572          SC                2           2.15000009537
            MST      MST          -- 103.830558777          DC               84                    16.0
         SST-1M      SST          1M 9.41809272766          SC               18           5.59999990463
 MST-Whipple10m      MST  Whipple10m          75.0          DC              248                     7.3
       SST-FACT      SST        FACT          9.51          DC               30                   4.889
>>> version = table.meta.get("TAB_VER")
>>> version

```

**Comment by maxnoe** [comment]
@SeiyaNozaki The `.from_name` methods in ctapipe download old description tables from the test data server, which come from prod3 example files, they are only meant for ctapipe unit tests and [we are thinking about removing them alltogether](https://github.com/cta-observatory/ctapipe/issues/1978)

For what concerns LST observed data, you can use:

```
from ctapipe_io_lst import OPTICS
```

or for the full subarray:

```
from ctapipe_io_lst import LSTEventSource

subarray = LSTEventSource.create_subarray()
```
