### ISSUE TITLE
Tests fail reading the file drive_log_20200218.txt from test_data

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#1094]
The tests in high_level do not pass in my Mac

```
lstchain/data/tests/test_normalised_pulse_template.py::test_load_from_file_and_miscellaneous PASSED [  4%]
lstchain/high_level/tests/test_hdus.py::test_create_event_list ERROR     [  5%]
lstchain/high_level/tests/test_hdus.py::test_create_obs_hdu_index ERROR  [  5%]
lstchain/high_level/tests/test_hdus.py::test_get_timing_params PASSED    [  6%]
lstchain/high_level/tests/test_interpolate.py::test_load_irf_grid PASSED [  6%]
lstchain/high_level/tests/test_interpolate.py::test_interp_irf FAILED    [  7%]
lstchain/high_level/tests/test_interpolate.py::test_compare_irfs PASSED  [  7%]

```
When looking in more detail, the error seems to be in the r0 to dl1 step, and specifically, in ctapipe_io_lst, when it tries to read in the drive report of the test data
https://github.com/cta-observatory/ctapipe_io_lst/blob/28b4a1b55e58fbacae6fe52c90b0e6e28433b984/ctapipe_io_lst/pointing.py#L96-L121

test_data/real/monitoring/DrivePositioning/drive_log_20200218.txt

```
astropy.io.ascii.core.InconsistentTableError: 
ERROR: Unable to guess table format with the guesses listed below:
[...]
```
And indeed, the format does not seem to be what it tries to read. I can reproduce it outside of the tests (either running the lstchain_data_r0_to_dl1 script, or directly trying to read in the file)...
`
astropy.io.ascii.core.InconsistentTableError: Length of names argument (10) does not match number of table columns (20) `

**Comment by moralejo** [comment]
This is enough to reproduce the error:

```
>>> from astropy.table import Table
>>> Table.read("test_data/real/monitoring/DrivePositioning/drive_log_20200218.txt", format='ascii', delimiter=' ', header_start=None, data_start=0, names=["weekday", "month", "day", "time", "year", "unix_time", "Az", "azimuth_correction", "Zd", "zenith_correction"], exclude_names=["weekday", "month", "day", "time", "year", "Az", "Zd"])

Traceback (most recent call last):
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/ascii/ui.py", line 509, in _guess
    dat = reader.read(table)
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/ascii/core.py", line 1341, in read
    self.header.check_column_names(self.names, self.strict_names, self.guessing)
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/ascii/core.py", line 743, in check_column_names
    raise InconsistentTableError(
astropy.io.ascii.core.InconsistentTableError: Length of names argument (10) does not match number of table columns (20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/table/connect.py", line 61, in __call__
    out = registry.read(cls, *args, **kwargs)
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/registry.py", line 527, in read
    data = reader(*args, **kwargs)
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/ascii/connect.py", line 18, in io_read
    return read(filename, **kwargs)
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/ascii/ui.py", line 334, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/Users/moralejo/opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/ascii/ui.py", line 540, in _guess
    raise core.InconsistentTableError('\n'.join(lines))

```

**Comment by maxnoe** [comment]
We switched to the new drive log format some versions ago. You need to use the DrivePosition... named files.

**Comment by gabemery** [comment]
The method to read the file you are trying is above the one you used "_read_drive_report". 
The issue is thus (as said above) that your tests are using the wrong file for some reason.

**Comment by moralejo** [comment]
Yes, but in the tests I did not choose the file myself... I just re-did what the tests did automatically.

And more mysterious of all: why do the tests pass in linux but not on OS X ?  (I just tried on freshly created envs in both)

**Comment by maxnoe** [comment]
The switch to the new drive reports was done in ctapipe_io_lst 0.19, lstchain requires 0.18.x

So you have a too new ctapipe_io_lst in your macos env for some reason. A fresh env shouldn't do that.

**Comment by moralejo** [comment]
It does not seem to be the case, looks like 0.18.2

```
>>> import ctapipe_io_lst
>>> ctapipe_io_lst.__version__
'0.18.2'
```

**Comment by moralejo** [comment]
[out_test_master.log](https://github.com/cta-observatory/cta-lstchain/files/11407466/out_test_master.log)

**Comment by rlopezcoto** [comment]
Hi, just tested on my mac and got the same error as @moralejo using the `master` branch of lstchain. I created a clean environment just to make sure and the error repeated. I also made sure of the `ctapipe_io_lst` version by pip installing it, but still got the same error as he is reporting above

**Comment by moralejo** [comment]
Thanks @rlopezcoto ! Very mysterious...

**Comment by maxnoe** [comment]
The error is that it tries to read the drive log with the code intended to read the bending model corrections. 

I don't have any idea yet why that might happen and only happen on macos..

**Comment by maxnoe** [comment]
Important part from the log:

```
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/ctapipe/io/eventsource.py:278: in __iter__
    for event in self._generator():
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/ctapipe_io_lst/__init__.py:420: in _generator
    self.fill_pointing_info(array_event)
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/ctapipe_io_lst/__init__.py:696: in fill_pointing_info
    pointing = self.pointing_source.get_pointing_position_altaz(
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/ctapipe_io_lst/pointing.py:162: in get_pointing_position_altaz
    self._read_drive_report_for_tel(tel_id)
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/ctapipe_io_lst/pointing.py:129: in _read_drive_report_for_tel
    self.drive_report[tel_id] = self._read_drive_report(path)
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/ctapipe_io_lst/pointing.py:76: in _read_drive_report
    corrections = PointingSource._read_bending_model_corrections(bending_path)
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/ctapipe_io_lst/pointing.py:101: in _read_bending_model_corrections
    return Table.read(
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/table/connect.py:61: in __call__
    out = registry.read(cls, *args, **kwargs)
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/registry.py:527: in read
    data = reader(*args, **kwargs)
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/ascii/connect.py:18: in io_read
    return read(filename, **kwargs)
../../../opt/miniconda3/envs/lst-dev/lib/python3.8/site-packages/astropy/io/ascii/ui.py:334: in read
    dat = _guess(table, new_kwargs, format, fast_reader)
```

You can see from the traceback, that it raises in `_read_bending_model_corrections`.

**Comment by maxnoe** [comment]
The tests should run through if you locally delete the new `BendingModelCorrection_log*` files. Could you confirm that?

**Comment by maxnoe** [comment]
Another solution would be to create a new volume using `Disk Utility` with a case insensitive file system (e.g. `APFS (Case sensitive)` and mount that and clone the lstchain repo there.

**Comment by moralejo** [comment]
> The tests should run through if you locally delete the new `BendingModelCorrection_log*` files. Could you confirm that?

They do, thanks!

**Comment by maxnoe** [comment]
I'd propose for now to not do any changes and just note this workaround here for the mac users.

Once we update to the new ctapipe_io_lst / ctapipe version, we can delete the old format drive log files from the test data and the issue will disappear.

**Comment by rlopezcoto** [comment]
thanks a lot for the investigation @maxnoe! I also confirm that tests run. 
Let's then leave this issue opened as a reminder to remove the old format drive log files whenever we update lstchain

**Comment by morcuended** [comment]
I think we can remove the old-format drive log files from the test sample already @maxnoe

**Comment by maxnoe** [comment]
We are just talking about making a bugfix release for 0.9 for the edisp issue here, right? #1160 

So I'd  not remove these files yet, they will be needed for running the tests on the 0.9.x branch we'll need to make that release.
