### ISSUE TITLE
DRS4 baseline creation script fails with ctapipe io lst 0.22.2 and EVB5 data

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#1178]
For DRS4 run 15451 (taken with EVB5)

Error traceback:
```python
2023-11-13 10:50:11,491 ERROR [lstchain.lstchain_create_drs4_pedestal_file] (tool.run): Caught unexpected exception: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/fefs/aswg/workspace/daniel.morcuende/.conda/envs/my-lstchain-v0.10.4/lib/python3.11/site-packages/ctapipe/core/tool.py", line 426, in run
    self.start()
  File "/fefs/aswg/workspace/daniel.morcuende/.conda/envs/my-lstchain-v0.10.4/lib/python3.11/site-packages/lstchain/tools/lstchain_create_drs4_pedestal_file.py", line 215, in start
    for event in tqdm(self.source, disable=not self.progress_bar):
  File "/fefs/aswg/workspace/daniel.morcuende/.conda/envs/my-lstchain-v0.10.4/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/fefs/aswg/workspace/daniel.morcuende/.conda/envs/my-lstchain-v0.10.4/lib/python3.11/site-packages/ctapipe/io/eventsource.py", line 323, in __iter__
    for event in self._generator():
  File "/fefs/aswg/workspace/daniel.morcuende/.conda/envs/my-lstchain-v0.10.4/lib/python3.11/site-packages/ctapipe_io_lst/__init__.py", line 642, in _generator
    self.r0_r1_calibrator.apply_drs4_corrections(array_event)
  File "/fefs/aswg/workspace/daniel.morcuende/.conda/envs/my-lstchain-v0.10.4/lib/python3.11/site-packages/ctapipe_io_lst/calibration.py", line 227, in apply_drs4_corrections
    for tel_id in event.trigger.tels_with_trigger:
TypeError: 'NoneType' object is not iterable
```

For run 15385 (second test night 2023-11-10 with EVB6, only with baseline correction applied). The script seem to work but with a CRITICAL message:
```python
2023-11-13 10:59:08,599 CRITICAL [lstchain.lstchain_create_drs4_pedestal_file] (lstchain_create_drs4_pedestal_file.finish): 8726424 baseline values are smaller than 0
2023-11-13 10:59:35,129 WARNING [lstchain.lstchain_create_drs4_pedestal_file] (lstchain_create_drs4_pedestal_file.finish): 15196159 baseline values are smaller than 25
```
probably related to the baseline subtraction file that was used by EVB?

**Comment by maxnoe** [comment]
No, it's a refactoring I did here. Needs a fix here (and a test), the drs4 pedestal script uses the option `trigger_information=False`, which results in trigger not being filled.
