### ISSUE TITLE
Problems in R0 to DL1 due to spoiled calibration coefficients

### ISSUE THREAD

**Issue by marialainez** [cta-observatory/cta-lstchain#1183]
The processing of the subrun 15748.0008, subruns 2, 3, 5, 7 of run 15749, subruns 1, 3, 5 of run 15750, subruns 0, 1 of run 15754 and subruns 1, 3, 5 of run 15755 from the day 2023-11-21 fail in the R0 to DL1 step. Here is an example of the one of the commands that we are running: 
```
lstchain_data_r0_to_dl1 --input-file=/fefs/aswg/data/real/R0/20231121/LST-1.1.Run15749.0005.fits.fz --output-dir=/fefs/aswg/data/real/running_analysis/20231121/v0.10 --pedestal-file=/fefs/aswg/data/real/monitoring/PixelCalibration/Cat-A/drs4_baseline/20231121/v0.10.2/drs4_pedestal.Run15765.0000.h5 --calibration-file=/fefs/aswg/data/real/monitoring/PixelCalibration/Cat-A/calibration/20231121/v0.10.4/calibration_filters_52.Run15766.0000.h5 --time-calibration-file=/fefs/aswg/data/real/monitoring/PixelCalibration/Cat-A/drs4_time_sampling_from_FF/20231102/v0.10.4/time_calibration.Run15253.0000.h5 --systematic-correction-file=/fefs/aswg/data/real/monitoring/PixelCalibration/Cat-A/ffactor_systematics/20230410/v0.10.3/calibration_scan_fit_20230410.0000.h5 --config=/fefs/aswg/lstosa/config_files_lstchain/lstchain_standard_v0.10_heuristic_ff.json --pointing-file=/fefs/onsite/monitoring/driveLST1/DrivePositioning/DrivePosition_log_20231121.txt --run-summary-path=/fefs/aswg/data/real/monitoring/RunSummary/RunSummary_20231121.ecsv
``` 

And here is the error traceback that we get:

```
/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/ctapipe/io/tableio.py:417: RuntimeWarning: invalid value encountered in cast
  result = scaled.astype(self.target_dtype)
/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/ctapipe/io/tableio.py:417: RuntimeWarning: invalid value encountered in cast
  result = scaled.astype(self.target_dtype)
Found large number of outliers in flatfield sample:
Outliers: 7 events with more than 50 pixels
Bad event index: [ 567 3171 3724 5055 7606 9624 9673]
Bad gain channel: [1 1 1 1 1 1 1]
Number of bad pixels in those entries: [ 87  96 458  58  51  68  65]
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/osa-v0.10/bin/lstchain_data_r0_to_dl1", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/lstchain/scripts/lstchain_data_r0_to_dl1.py", line 227, in main
    r0_to_dl1.r0_to_dl1(
  File "/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/lstchain/reco/r0_to_dl1.py", line 520, in r0_to_dl1
    new_ped_event, new_ff_event = calibration_calculator.process_interleaved(event)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/lstchain/calib/camera/calibration_calculator.py", line 273, in process_interleaved
    self.calculate_calibration_coefficients(event)
  File "/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/lstchain/calib/camera/calibration_calculator.py", line 176, in calculate_calibration_coefficients
    signal = ff_data.charge_median - ped_data.charge_median
             ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
Closing remaining open files:/fefs/aswg/data/real/running_analysis/20231121/v0.10/interleaved_LST-1.Run15749.0005.h5...done
```

**Comment by maxnoe** [comment]
I guess this error comes from missing flatfield or pedestal events?

@FrancaCassol

**Comment by SeiyaNozaki** [comment]
I don't know if it is related or not, but those runs were taken with somehow reduced HV due to the moon according to the log. I can see calibration signals and pedestal events, but can be regarded as bad events...?

**Comment by maxnoe** [comment]
@SeiyaNozaki yes, I think this is relevant since we are missing proper event types for some reason and with the reduced high voltage and moon light, the flat field heuristic probably didn't work.

**Comment by morcuended** [comment]
@moralejo suggested osa keep going using the flat field heuristic flag regardless if the calibration trigger information is properly propagated to the events. We could maybe stop using it for newer data if that is problematic in cases like these.

**Comment by FrancaCassol** [comment]
mmh, we should not arrive there if FF or pedestals are missing, something is going wrong also in the code, I will have a look

**Comment by marialainez** [comment]
we had this error again for subrun 18144.0023 from 20240708, for the moment we discarded this subrun from being processed

**Comment by marialainez** [comment]
We had this error again on 20240805 for subruns 18448.0002, 18448.0007 and 18449.0007, which were discarded from being processed.

**Comment by morcuended** [comment]
This keeps happening now and then. @FrancaCassol could you please have a look?

**Comment by moralejo** [comment]
@marialainez  are these again moon (low-HV) runs?  Does the analysis fail also if the heuristic identification is switched off?

**Comment by morcuended** [comment]
The latest occurrence was 2024-08-26 (file 18690.0007, very low rates during those observations)

For the 20240805 indeed the affected runs were problematic, rate control was not properly working due to LIDAR (https://www.lst1.iac.es/datacheck/observation_overview/2024/08/run_summary_2024_08_05.pdf)

I usually see this when there are spikes in the rates, so it is probably due to the misidentification of FF events

Currently, OSA is not using heuristic identification and it is hard for the OSA team to decide which config to use depending on the date, runs, etc. An automatic solution should be desirable (use the heuristic approach for a given event if normal identification fails?)

**Comment by moralejo** [comment]
> 
> Currently, OSA is not using heuristic identification and it is hard for the OSA team to decide which config to use depending on the date, runs, etc. An automatic solution should be desirable (use the heuristic approach for a given event if normal identification fails?)

I don't understand, we cannot know on an event-wise basis if the heuristic failed. If anything, we can know it failed for a subrun after checking some distributions - and even that may not be 100% reliable. I think we should stop patching these issues and just declare data without proper even tagging as lost. I am pretty sure correct tagging is a requirement.

**Comment by morcuended** [comment]
Ok, forget about my comment. I agree with your proposal. Regarding incorrect tagging of calibration events, we will discard those affected files. Maybe what we need is a clear raised error when this happens
