### ISSUE TITLE
'mamba create' generates an environment with scikit-learn=1.3.2, which breaks compatibility

### ISSUE THREAD

**Issue by mireianievas** [cta-observatory/cta-lstchain#1195]
Can anyone cross-check if generating a clean mamba create  installs scikit-learn=1.3.2. In my case it seems to be doing that (despite seeing that in the environment in the main version it is forced 1.2). It results in a non-working lstchain environment

Steps:

```
mamba create -c conda-forge -n lstchain-v0.10.5 python=3.11 lstchain=0.10.5
```

Errors I was getting using that version of sklearn through the dl1_to_dl2

```
/home/mireia.nievas/workspace/software/miniconda/envs/lstchain-v0.10.5/lib/python3.11/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeRegressor from version 1.2.2 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "/home/mireia.nievas/workspace/software/miniconda/envs/lstchain-v0.10.5/bin/lstchain_dl1_to_dl2", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mireia.nievas/workspace/software/miniconda/envs/lstchain-v0.10.5/lib/python3.11/site-packages/lstchain/scripts/lstchain_dl1_to_dl2.py", line 270, in main
    models_dict = {'reg_energy': joblib.load(Path(args.path_models, 'reg_energy.sav'))}
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(  ...  )

ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
```

**Comment by vuillaut** [comment]
latest action for python 3.11 installs scikit-learn v1.2.2 as required:
https://github.com/cta-observatory/cta-lstchain/actions/runs/7209210412/job/19639699946

so did  v0.10.5:
https://github.com/cta-observatory/cta-lstchain/actions/runs/7059201791/job/19216322629

**Comment by mireianievas** [comment]
Ok, strange.

**Comment by morcuended** [comment]
mamba create -c conda-forge -n lstchain-v0.10.5 python=3.11 lstchain=0.10.5

is actually giving me problems in both linux and macos:
```
Could not solve for environment specs
The following package could not be installed
└─ lstchain 0.10.5**  is uninstallable because it requires
   └─ python-blosc2  , which does not exist (perhaps a missing channel).
```

**Comment by maxnoe** [comment]
The package definitely exists:
https://anaconda.org/conda-forge/python-blosc2/files?version=2.3.2

**Comment by vuillaut** [comment]
```
docker run -it mambaorg/micromamba
micromamba create -c conda-forge -n lstchain-v0.10.5 python=3.11 lstchain=0.10.5
micromamba activate lstchain-v0.10.5
python -c 'import lstchain; print(lstchain.__version__)'
0.10.5
```
works fine

**Comment by mireianievas** [comment]
ok, lets close then.

**Comment by morcuended** [comment]
> The package definitely exists:
> https://anaconda.org/conda-forge/python-blosc2/files?version=2.3.2

Just a correction on this. It actually worked fine on linux, but not on macos (my bad!)
