### ISSUE TITLE
EVBPreprocessing vs EVBPreprocessingFlag incompatibility in lstchain v0.10.7

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#1244]
It seems there is an incompatibility between lstchain 0.10.7 (using EVBPreprocessing) and ctapipe io lst 0.23.1 (using EVBPreprocessingFlag)
```
# Name                    Version                   Build  Channel
ctapipe-io-lst            0.23.1                   pypi_0    pypi
lstchain                  0.10.7                   pypi_0    pypi
```

```python
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/osa-v0.10/bin/lstchain_create_drs4_pedestal_file", line 5, in <module>
    from lstchain.tools.lstchain_create_drs4_pedestal_file import main
  File "/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/lstchain/tools/lstchain_create_drs4_pedestal_file.py", line 17, in <module>
    from ctapipe_io_lst import LSTEventSource, EVBPreprocessing, TriggerBits
ImportError: cannot import name 'EVBPreprocessing' from 'ctapipe_io_lst' (/fefs/aswg/software/conda/envs/osa-v0.10/lib/python3.11/site-packages/ctapipe_io_lst/__init__.py)
```
The main lstchain branch is fine though after #1240

**Comment by morcuended** [comment]
Indeed, it is how it should. lstchain 0.10.7 requires io lst 0.22.X, and we were using already 0.23.X to deal with other problems fixed in the latest io lst release.

Closing this
