### ISSUE TITLE
FileNotFoundError: lstchain/data/SinglePhE_ResponseInPhE_expo2Gaus.dat not found

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/cta-lstchain#1253]
Hi

With lstchain >= v0.10.7 I get the following error when running `lstchain_mc_r0_to_dl1`:

```
FileNotFoundError: lstchain/data/SinglePhE_ResponseInPhE_expo2Gaus.dat not found
```

**Comment by vuillaut** [comment]
Found the source of the error, working on it.

**Comment by morcuended** [comment]
I think we should use importlib to get these package data files.

Offtopic: I tried to run `lstchain_mc_r0_to_dl1` with v0.10.11 and gave me this error:
```
Downloading gamma_test_large.simtel.gz ...

Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.11/bin/lstchain_mc_r0_to_dl1", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.11/lib/python3.11/site-packages/lstchain/scripts/lstchain_mc_r0_to_dl1.py", line 74, in main
    r0_to_dl1.r0_to_dl1(
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.11/lib/python3.11/site-packages/lstchain/reco/r0_to_dl1.py", line 352, in r0_to_dl1
    source = EventSource(input_url=input_filename,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.11/lib/python3.11/site-packages/ctapipe/io/simteleventsource.py", line 512, in __init__
    self._subarray_info = self.prepare_subarray_info(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.11/lib/python3.11/site-packages/ctapipe/io/simteleventsource.py", line 643, in prepare_subarray_info
    raise RuntimeError(
RuntimeError: `SimTelEventSource.focal_length_choice` was set to 'EFFECTIVE', but the effective focal length was not present in the file. Set `focal_length_choice='EQUIVALENT'` or make sure input files contain the effective focal length
```

**Comment by vuillaut** [comment]
> I think we should use importlib to get these package data files.

Yes... There is no way this script could work without modifying the config.
