### ISSUE TITLE
Error when merging DL1 files

### ISSUE THREAD

**Issue by lfoffano** [cta-observatory/cta-lstchain#287]
Dear all,

I am trying to merge DL1 files in a folder named "20191126", but I get this error:

(lst) [luca.foffano@cp02 dl1]$ lstchain_merge_hdf5_files -d 20191126 -o 20191126/results
/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/corsikaio/subblocks/dtypes.py:20: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  return np.dtype(dict(**dt))
/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/bin/lstchain_merge_hdf5_files", line 11, in <module>
    load_entry_point('lstchain', 'console_scripts', 'lstchain_merge_hdf5_files')()
  File "/fefs/aswg/workspace/luca.foffano/software/cta-lstchain/lstchain/scripts/lstchain_merge_hdf5_files.py", line 48, in main
    smart_merge_h5files(file_list, args.outfile, node_keys=keys)
  File "/fefs/aswg/workspace/luca.foffano/software/cta-lstchain/lstchain/io/io.py", line 250, in smart_merge_h5files
    merging_check(file_list)
  File "/fefs/aswg/workspace/luca.foffano/software/cta-lstchain/lstchain/io/io.py", line 227, in merging_check
    mcheader0 = read_simu_info_hdf5(filename0)
  File "/fefs/aswg/workspace/luca.foffano/software/cta-lstchain/lstchain/io/io.py", line 58, in read_simu_info_hdf5
    mc = next(mcheader)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 411, in read
    tab = self._setup_table(table_name, container)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 337, in _setup_table
    tab = self._h5file.get_node(table_name)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/tables/file.py", line 1642, in get_node
    node = self._get_node(nodepath)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/tables/file.py", line 1590, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/tables/file.py", line 432, in get_node
    node = self.node_factory(key)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/tables/group.py", line 1178, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/simulation/run_config``

Have you any suggestion about this?

Thank you very much
Luca

**Comment by morcuended** [comment]
Hi @lfoffano 
Try to run it with --smart False

**Comment by lfoffano** [comment]
@morcuended Thank you very much for the fast reply!
 Now I get this error:

(lst) [luca.foffano@cp02 dl1]$ lstchain_merge_hdf5_files -d 20191126 -o 20191126/results --smart False
/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/corsikaio/subblocks/dtypes.py:20: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  return np.dtype(dict(**dt))
/home/luca.foffano/workspace/software/miniconda3/envs/lst/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst/bin/lstchain_merge_hdf5_files", line 11, in <module>
    load_entry_point('lstchain', 'console_scripts', 'lstchain_merge_hdf5_files')()
  File "/fefs/aswg/workspace/luca.foffano/software/cta-lstchain/lstchain/scripts/lstchain_merge_hdf5_files.py", line 50, in main
    auto_merge_h5files(file_list, args.outfile, nodes_keys=keys)
  File "/fefs/aswg/workspace/luca.foffano/software/cta-lstchain/lstchain/io/io.py", line 175, in auto_merge_h5files
    keys = get_dataset_keys(file_list[0])
IndexError: list index out of range

**Comment by vuillaut** [comment]
> Dear all,
> 
> I am trying to merge DL1 files in a folder named "20191126", but I get this error:
> 
> (lst) [luca.foffano@cp02 dl1]$ lstchain_merge_hdf5_files -d 20191126 -o 20191126/results

Hi @lfoffano 

First comment, -o points to the outptut **file** some you might want to give it an extension *.h5*.

Second comment, it seems the directory you are pointing does not contain any *.h5* file (`file_list`has 0 elements in it).
*smart* is here to make sure you are merging compatible files.

**Comment by lfoffano** [comment]
Hi Thomas @vuillaut !

Thank you for the information. I am sorry, I put only the output folder and not the output file.

However, I did some tests and I see that it works ONLY when deactivating the smart function (otherwise I get the same error of my first post). I do not know if this is related to the fact that in my folder I have both h5 files and another folder  named"results".

(lst) [luca.foffano@cp02 dl1]$ ls 20191126/
dl1_LST-1.1.Run01651.0000.fits.h5  dl1_LST-1.1.Run01651.0010.fits.h5  
[...]
dl1_LST-1.1.Run01651.0008.fits.h5  dl1_LST-1.1.Run01651.0028.fits.h5  results/

Thank you all very much for your fast help!
I close the thread, solved!

Cheers

**Comment by morcuended** [comment]
> However, I did some tests and I see that it works ONLY when deactivating the smart function (otherwise I get the same error of my first post). I do not know if this is related to the fact that in my folder I have both h5 files and another folder named"results".

Same happens to me. I would say the reason is that the smart option was first thought to be used with MC data since it involves functions as `read_simu_info_hdf5` in which the code does the checkings. It is actually there where the error raises as it is trying to find `/simulation/run_config` table in real data files. So the error:

```
Traceback (most recent call last):
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/bin/lstchain_merge_hdf5_files", line 11, in <module>
    load_entry_point('lstchain', 'console_scripts', 'lstchain_merge_hdf5_files')()
  File "/fefs/aswg/software/virtual_env/ctasoft/cta-lstchain/lstchain/scripts/lstchain_merge_hdf5_files.py", line 48, in main
    smart_merge_h5files(file_list, args.outfile, node_keys=keys)
  File "/fefs/aswg/software/virtual_env/ctasoft/cta-lstchain/lstchain/io/io.py", line 250, in smart_merge_h5files
    merging_check(file_list)
  File "/fefs/aswg/software/virtual_env/ctasoft/cta-lstchain/lstchain/io/io.py", line 227, in merging_check
    mcheader0 = read_simu_info_hdf5(filename0)
  File "/fefs/aswg/software/virtual_env/ctasoft/cta-lstchain/lstchain/io/io.py", line 58, in read_simu_info_hdf5
    mc = next(mcheader)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 411, in read
    tab = self._setup_table(table_name, container)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe/io/hdf5tableio.py", line 337, in _setup_table
    tab = self._h5file.get_node(table_name)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/file.py", line 1642, in get_node
    node = self._get_node(nodepath)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/file.py", line 1590, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/file.py", line 432, in get_node
    node = self.node_factory(key)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/group.py", line 1178, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/cta/lib/python3.7/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/simulation/run_config``
```

Perhaps, the smart option should take into account that now we can also merge real data files.

**Comment by vuillaut** [comment]
> > However, I did some tests and I see that it works ONLY when deactivating the smart function (otherwise I get the same error of my first post). I do not know if this is related to the fact that in my folder I have both h5 files and another folder named"results".
> 
> Same happens to me. I would say the reason is that the smart option was first thought to be used with MC data since it involves functions as `read_simu_info_hdf5` in which the code does the checkings. It is actually there where the error raises as it is trying to find `/simulation/run_config` table in real data files. 
> 
> Perhaps, the smart option should take into account that now we can also merge real data files.

Thanks for reporting  @morcuended I'll have a look.
