### ISSUE TITLE
DL1 -> DL2 lstchain v0.5.1:    ValueError: invalid compression library id: 10

### ISSUE THREAD

**Issue by lfoffano** [cta-observatory/cta-lstchain#441]
Dear all,

I am trying to reproduce the step from DL1 to DL2 of some dates. Using the DL1 files already available, I get this error:

```
(lst-0.5.1) [luca.foffano@cp02 scripts]$ lstchain_dl1_to_dl2 --input-file /fefs/aswg/data/real/DL1/20200215/v0.5.1_v03/dl1_LST-1.Run01992.0000.h5  --output-dir /home/luca.foffano/workspace/real_data/dl2/20200215/   --path-models /fefs/aswg/data/models/20190415/south_pointing/20200514_v0.5.1_v01
Traceback (most recent call last):
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/bin/lstchain_dl1_to_dl2", line 33, in <module>
    sys.exit(load_entry_point('lstchain', 'console_scripts', 'lstchain_dl1_to_dl2')())
  File "/fefs/aswg/workspace/luca.foffano/software/new_version/cta-lstchain/lstchain/scripts/lstchain_dl1_to_dl2.py", line 92, in main
    data = pd.read_hdf(args.input_file, key=dl1_params_lstcam_key)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/pandas/io/pytables.py", line 537, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/pandas/io/pytables.py", line 680, in open
    raise err
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/pandas/io/pytables.py", line 655, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/tables/file.py", line 813, in __init__
    root._g_post_init_hook()
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/tables/group.py", line 259, in _g_post_init_hook
    if 'VERSION' in self._v_attrs._v_attrnamessys:
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/tables/utils.py", line 240, in newfget
    mydict[name] = value = fget(self)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/tables/node.py", line 173, in _v_attrs
    return self._AttributeSet(self)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/tables/attributeset.py", line 248, in __init__
    self.__getattr__(attr)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/tables/attributeset.py", line 373, in __getattr__
    retval = Filters._unpack(value)
  File "/home/luca.foffano/workspace/software/miniconda3/envs/lst-0.5.1/lib/python3.7/site-packages/tables/filters.py", line 260, in _unpack
    % complib_id)
ValueError: invalid compression library id: 10
Closing remaining open files:/fefs/aswg/data/real/DL1/20200215/v0.5.1_v03/dl1_LST-1.Run01992.0000.h5...done
```

No output is produced. Changing models (all of may 2020 in the same folder) or changing config file doesn't help.

Do you have any idea on what is causing this compression problem? Am I doing anything wrong? 

Thank you very much
Cheers
Luca

**Comment by morcuended** [comment]
I cannot reproduce this error using lstchain v0.5.1 (`cta` common conda environment) nor master version with the same command you used (just changing the output dir).

**Comment by lfoffano** [comment]
ok so probably it is related to my installation of lstchain, I am checking.

Thank you
