### ISSUE TITLE
Tables error opening DL1 images v0.5.1

### ISSUE THREAD

**Issue by ricrando** [cta-observatory/cta-lstchain#508]
Hi
I have been trying to access the images in DL1 files following the example in [https://github.com/cta-observatory/cta-lstchain/issues/220](https://github.com/cta-observatory/cta-lstchain/issues/220) and it works with DL1 files version v0.4.4_v00, but I get an exception from tables in the case of files version v0.5.1_v03.
My code:
```
import tables
from lstchain.io.io import dl1_images_lstcam_key

#filename="DL1/crab/v0.4.4_v00/dl1_LST-1.1.Run02036.0000.fits.h5"
filename="DL1/crab/v0.5.1_v03/dl1_LST-1.Run02036.0000.h5"

file = tables.open_file(filename).root 
table = file[dl1_images_lstcam_key]
images = table[:]['image']
print(len(images))

```
The error:
```
Traceback (most recent call last):
  File "test3.py", line 7, in <module>
    file = tables.open_file(filename).root 
  File "/opt/conda/lst-chain/lib/python3.7/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/opt/conda/lst-chain/lib/python3.7/site-packages/tables/file.py", line 813, in __init__
    root._g_post_init_hook()
  File "/opt/conda/lst-chain/lib/python3.7/site-packages/tables/group.py", line 259, in _g_post_init_hook
    if 'VERSION' in self._v_attrs._v_attrnamessys:
  File "/opt/conda/lst-chain/lib/python3.7/site-packages/tables/utils.py", line 240, in newfget
    mydict[name] = value = fget(self)
  File "/opt/conda/lst-chain/lib/python3.7/site-packages/tables/node.py", line 173, in _v_attrs
    return self._AttributeSet(self)
  File "/opt/conda/lst-chain/lib/python3.7/site-packages/tables/attributeset.py", line 248, in __init__
    self.__getattr__(attr)
  File "/opt/conda/lst-chain/lib/python3.7/site-packages/tables/attributeset.py", line 373, in __getattr__
    retval = Filters._unpack(value)
  File "/opt/conda/lst-chain/lib/python3.7/site-packages/tables/filters.py", line 260, in _unpack
    % complib_id)
ValueError: invalid compression library id: 10

```
I am using lstchain 0.6.0 and tables 3.6.1.

**Comment by moralejo** [comment]
Hi had the same problem, seems related to the pytables installation, see:

https://github.com/PyTables/PyTables/issues/811

Unfortunately it seems nobody has answered. Can you try a different computer / installation?

**Comment by moralejo** [comment]
See also: https://ctapipe.slack.com/archives/CFCCQMP6V/p1595271005038000
If I remember correctly, a workaround is to downgrade the blosc module.

**Comment by rlopezcoto** [comment]
It is a bit strange, because using lstchain v0.5.1 (ctapipe v0.7.0) and the same tables version, the problem does not appear. Also reported in #441, but @lfoffano seemed to have solved it (how?)

The current installed version in the IT cluster has this problem, so if a workaround is found, we should implement something in lstchain until https://github.com/PyTables/PyTables/pull/812 gets accepted (and it is available in a new release).

@moralejo did `conda install blosc=1.16` work?

**Comment by ricrando** [comment]
> See also: https://ctapipe.slack.com/archives/CFCCQMP6V/p1595271005038000
> If I remember correctly, a workaround is to downgrade the blosc module.

Whee, what a read. 
I confirm that removing the FILTER attributes using maxnoe's script makes the files readable.

**Comment by moralejo** [comment]
> 
> @moralejo did `conda install blosc=1.16` work?

Yes it did.

**Comment by SeiyaNozaki** [comment]
`pip uninstall tables` and `pip install tables` also solved this issue...
But the version of `tables` is same before/after reinstallation...

**Comment by rlopezcoto** [comment]
and the `blosc` version?

**Comment by SeiyaNozaki** [comment]
I didn't check `blosc` version, just reinstall the tables at that time...

**Comment by rlopezcoto** [comment]
ok, I realized there is a new `blosc` version (v1.20) and it works with this one...

**Comment by ricrando** [comment]
> ok, I realized there is a new `blosc` version (v1.20) and it works with this one...

In my conda `blosc` is v1.20 though

**Comment by MaxNoe** [comment]
As explained in the slack chat it id not an issue of the blosc version  but a question against which set of compression linraries blosc was compiled.

This can differ for the same version of blosc as these are optional, build-time dependencies.

**Comment by MaxNoe** [comment]
The PR was just merged: https://github.com/PyTables/PyTables/pull/812

Should be in the next pytables release.
