### ISSUE TITLE
prod5 files fail at `r0_dl1` stage

### ISSUE THREAD

**Issue by garciagenrique** [cta-observatory/cta-lstchain#538]
Hi all,

Running the `lstchain_mc_r0_to_dl1` stage for new MC prod5 files I found the following error;
```
WARNING: AstropyDeprecationWarning: this function will disappear in lstchain v0.7 [lstchain.reco.r0_to_dl1]
WARNING during lstchain.io.write_array_info(): camera MAGICCam seems to be already present in the h5 file.
WARNING: AstropyDeprecationWarning: this function will disappear in lstchain v0.7 [lstchain.reco.r0_to_dl1]
Traceback (most recent call last):
  File "/fefs/aswg/workspace/enrique.garcia/miniconda3/envs/lst-dev/bin/lstchain_mc_r0_to_dl1", line 33, in <module>
    sys.exit(load_entry_point('lstchain', 'console_scripts', 'lstchain_mc_r0_to_dl1')())
  File "/fefs/home/enrique.garcia/software/cta-lstchain/lstchain/scripts/lstchain_mc_r0_to_dl1.py", line 69, in main
    custom_config=config,
  File "/fefs/home/enrique.garcia/software/cta-lstchain/lstchain/reco/r0_to_dl1.py", line 308, in r0_to_dl1
    write_array_info_08(subarray, output_filename)
  File "/fefs/aswg/workspace/enrique.garcia/miniconda3/envs/lst-dev/lib/python3.7/site-packages/astropy/utils/decorators.py", line 124, in deprecated_func
    return func(*args, **kwargs)
  File "/fefs/home/enrique.garcia/software/cta-lstchain/lstchain/io/io.py", line 371, in write_array_info_08
    stage1._write_instrument_configuration(subarray)
  File "/fefs/aswg/workspace/enrique.garcia/miniconda3/envs/lst-dev/lib/python3.7/site-packages/ctapipe/tools/stage1.py", line 407, in _write_instrument_configuration
    serialize_meta=serialize_meta,
  File "/fefs/aswg/workspace/enrique.garcia/miniconda3/envs/lst-dev/lib/python3.7/site-packages/astropy/table/connect.py", line 113, in __call__
    registry.write(instance, *args, **kwargs)
  File "/fefs/aswg/workspace/enrique.garcia/miniconda3/envs/lst-dev/lib/python3.7/site-packages/astropy/io/registry.py", line 566, in write
    writer(data, *args, **kwargs)
  File "/fefs/aswg/workspace/enrique.garcia/miniconda3/envs/lst-dev/lib/python3.7/site-packages/astropy/io/misc/hdf5.py", line 306, in write_table_hdf5
    serialize_meta=serialize_meta)
  File "/fefs/aswg/workspace/enrique.garcia/miniconda3/envs/lst-dev/lib/python3.7/site-packages/astropy/io/misc/hdf5.py", line 323, in write_table_hdf5
    raise OSError(f"Table {path} already exists")
OSError: Table /configuration/instrument/telescope/camera/geometry_MAGICCam already exists
```

[edit - Not opening the correct dl1 file]

```
In [3]: hf.root.configuration.instrument.telescope.camera
Out[3]: 
/configuration/instrument/telescope/camera (Group) ''
  children := ['geometry_LSTCam' (Table), 'geometry_LSTCam.__table_column_meta__' (Array), 'geometry_MAGICCam' (Table), 'geometry_MAGICCam.
__table_column_meta__' (Array), 'readout_LSTCam' (Table), 'readout_LSTCam.__table_column_meta__' (Array), 'readout_MAGICCam' (Table), 'read
out_MAGICCam.__table_column_meta__' (Array)]
```

**Comment by garciagenrique** [comment]
Commenting `write_array_info_08` (line 308 of `r0_to_dl1.py`) avoids the error, although triggers some other pyTables warnings.

However, this warnings also appeared when performing the `r0_to_dl1` stage for prod3 (to be honest, I just realise about it).

```
WARNING: AstropyDeprecationWarning: this function will disappear in lstchain v0.7 [lstchain.reco.r0_to_dl1]
WARNING during lstchain.io.write_array_info(): camera MAGICCam seems to be already present in the h5 file.
Column tels_with_data of container DL0Container in table subarray/mc_shower not writable, skipping
Column tel of container DL0Container in table subarray/mc_shower not writable, skipping
Column mc_tel of container MCEventContainer in table subarray/mc_shower not writable, skipping
Column tels_with_data of container DL0Container in table subarray/trigger not writable, skipping
Column tel of container DL0Container in table subarray/trigger not writable, skipping
Column tel of container TriggerContainer in table subarray/trigger not writable, skipping
Column tels_with_data of container R0Container in table telescope/image/LST_LSTCam not writable, skipping
Column tel of container R0Container in table telescope/image/LST_LSTCam not writable, skipping
Column image_mask of container DL1CameraContainer in table telescope/image/LST_LSTCam not writable, skipping
Column parameters of container DL1CameraContainer in table telescope/image/LST_LSTCam not writable, skipping
Column disp_norm of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column disp_dx of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column disp_dy of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column disp_angle of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column disp_sign of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column disp_miss of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column src_x of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column src_y of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column alt_tel of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column az_tel of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column dragon_time of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column ucts_time of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column tib_time of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column mc_shower_primary_id of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column hadroness of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column ucts_trigger_type of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Column trigger_time of container DL1ParametersContainer in table telescope/parameters/LST_LSTCam not writable, skipping
Not valid UCTS timestamp found
Not valid TIB counter value found
```

**Comment by SeiyaNozaki** [comment]
This issue is also discussed in #514

**Comment by garciagenrique** [comment]
Ok, closing and moving to #514
