### ISSUE TITLE
lstchain_create_calibration_file broken

### ISSUE THREAD

**Issue by Bultako** [cta-observatory/cta-lstchain#627]
I cannot produce a calibration file with tool `lstchain_create_calibration_file`. I have the following error.

```
$ lstchain_create_calibration_file --input_file LST-1.1.Run03513.0000.fits.fz 
--config lstchain/data/onsite_camera_calibration_param.json

[...]
[...]
[...]

ERROR [ctapipe.CalibrationHDF5Writer] (tool.run): Caught unexpected exception: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/opt/miniconda3/envs/lst-dev-2/lib/python3.7/site-packages/ctapipe/core/tool.py", line 260, in run
    self.start()
  File "/Users/jer/git/cta-observatory/cta-lstchain/lstchain/tools/lstchain_create_calibration_file.py", line 166, in start
    new_ped = self.processor.pedestal.calculate_pedestals(event)
  File "/Users/jer/git/cta-observatory/cta-lstchain/lstchain/calib/camera/pedestals.py", line 148, in calculate_pedestals
    self.setup_sample_buffers(waveform, self.sample_size)
  File "/Users/jer/git/cta-observatory/cta-lstchain/lstchain/calib/camera/pedestals.py", line 217, in setup_sample_buffers
    n_channels = waveform.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by rlopezcoto** [comment]
thanks @Bultako for reporting. 
This does not seem to be related anymore to #620 but something introduced in one of the latest changes in the code updates, @Bultako can give more details. @FrancaCassol could you please have a look and see if you can reproduce it?

**Comment by Bultako** [comment]
Yep, it seems related with PR #587

**Comment by FrancaCassol** [comment]
Hi @Bultako,
I guess that the problem is due to the fact that  you did not give the drs4 pedestal file.
This should be not accepted. I will add a check

**Comment by Bultako** [comment]
Hi @FrancaCassol 

You're right, I can now produce the calibration file with the following command 

```
lstchain_create_calibration_file --input_file LST-1.1.Run03513.0000.fits.fz 
--config lstchain/data/onsite_camera_calibration_param.json
--LSTEventSource.LSTR0Corrections.drs4_pedestal_path drs4_pedestal.fits
```

Yes, it will be good to have this option at least displayed in the `--help-all`

**Comment by FrancaCassol** [comment]
yes, this should be feasible, I will look into that

**Comment by maxnoe** [comment]
You need to add `classes = [EventSource, ...]` to the `Tool`, also list all other `Components` you are using.

`classes` controls which traitlets appear in `--help-all`

**Comment by FrancaCassol** [comment]
actually it is already there, the problem is that I must add LSTEventSource

**Comment by maxnoe** [comment]
@FrancaCassol yes, or replace `EventSource` with `classes_with_traits(EventSource)`, which will show options for all available event classes (maybe not necessary here or should this script also work for simtel files?)

**Comment by FrancaCassol** [comment]
Ok. Yes, it was used to work also with simtel files, but I admit I did not check it after the last major changes

**Comment by Bultako** [comment]
Actually, I was just waiting to understand how to produce calibration files with this tool to finish the PR #598, I could add these improvements to #598

**Comment by FrancaCassol** [comment]
It is a rather old PR, isn't it? 
This tool is pretty clean now
I have an ongoing PR on the onsite scripts, I added already the change there.

**Comment by Bultako** [comment]
I have been updating it to last modifs made on the tool, and also adding tests with data.
But, yes I can wait you merge your ongoing PR on the onsite scripts.

**Comment by FrancaCassol** [comment]
Ok. I will add also the check on the drs4 file

**Comment by rlopezcoto** [comment]
> I have an ongoing PR on the onsite scripts, I added already the change there.

Are you talking about #623 @FrancaCassol?
Please let us try for the future to reduce the size of the PRs and fix one thing per PR, otherwise we will end up again with _monster_ PRs that are very difficult to review and reference later when trying to find where something was changed.

I suggest to open a new PR to make the modifications you are discussing.

**Comment by rlopezcoto** [comment]
in any case, good that the Issue was found, thanks for checking!

**Comment by FrancaCassol** [comment]
Hi @rlopezcoto,
> Are you talking about #623 @FrancaCassol?

no, it is an other PR (but I can do  a single one for this  if you prefer). By the way, if #623 is ok, it will better to have it merged before.

**Comment by rlopezcoto** [comment]
> no, it is an other PR (but I can do a single one for this if you prefer). By the way, if #623 is ok, it will better to have it merged before.

no please, as said above, let's try to keep PR as short as possible and also focused on adding/removing a given functionality.

**Comment by FrancaCassol** [comment]
Ok, then I do two other PRs
