### ISSUE TITLE
ValueError during addition of disp parameters during R0 to DL1 conversion

### ISSUE THREAD

**Issue by mexanick** [cta-observatory/cta-lstchain#633]
I’m trying to run the MC R0 to DL1 conversion using the most recent lstchain and have encountered a following issue. While some files pass the conversion just ok, some other issue a following error:
```shell
  File "/home/mykhailo.dalchenko/.conda/envs/lst-dev-03032021/lib/python3.7/site-packages/numpy/core/records.py", line 746, in fromrecords
    retval = sb.array(recList, dtype=descr)
ValueError: could not assign tuple of length 55 to structure with 54 fields.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mykhailo.dalchenko/.conda/envs/lst-dev-03032021/lib/python3.7/site-packages/tables/table.py", line 2221, in append
    wbufRA = numpy.rec.array(rows, dtype=self._v_dtype)
  File "/home/mykhailo.dalchenko/.conda/envs/lst-dev-03032021/lib/python3.7/site-packages/numpy/core/records.py", line 1069, in array
    return fromrecords(obj, dtype=dtype, shape=shape, **kwds)
  File "/home/mykhailo.dalchenko/.conda/envs/lst-dev-03032021/lib/python3.7/site-packages/numpy/core/records.py", line 758, in fromrecords
    _array[k] = tuple(recList[k])
ValueError: could not assign tuple of length 55 to structure with 54 fields.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mykhailo.dalchenko/.conda/envs/lst-dev-03032021/bin/convert_r0_to_dl1", line 8, in <module>
    sys.exit(main())
  File "/home/mykhailo.dalchenko/.conda/envs/lst-dev-03032021/lib/python3.7/site-packages/sim_runner/scripts/convert_r0_to_dl1.py", line 64, in main
    custom_config=config,
  File "/fefs/aswg/workspace/mykhailo.dalchenko/small_pix_cam/sw/cta-lstchain/lstchain/reco/r0_to_dl1.py", line 572, in r0_to_dl1
    add_disp_to_parameters_table(output_filename, f'dl1/event/telescope/parameters/{tel_name}', focal)
  File "/fefs/aswg/workspace/mykhailo.dalchenko/small_pix_cam/sw/cta-lstchain/lstchain/reco/r0_to_dl1.py", line 623, in add_disp_to_parameters_table
    add_column_table(tab, tables.Float32Col, 'disp_dx', disp_parameters[0].value)
  File "/fefs/aswg/workspace/mykhailo.dalchenko/small_pix_cam/sw/cta-lstchain/lstchain/io/io.py", line 947, in add_column_table
    newtable.append([tuple(list(row[:]) + [value])])
  File "/home/mykhailo.dalchenko/.conda/envs/lst-dev-03032021/lib/python3.7/site-packages/tables/table.py", line 2225, in append
    "The error was: <%s>" % (str(self), exc))
ValueError: rows parameter cannot be converted into a recarray object compliant with table '/_temp_table (Table(0,), fletcher32, shuffle, blosc:zstd(5)) '''. The error was: <could not assign tuple of length 55 to structure with 54 fields.>
```
This is happening at the very end of the conversion (actually augmenting existing h5 file with the disp parameters. Moreover, even with such error the affected h5 file looks ok and these additional 9 columns appear to be filled properly.

package versions:
Name: lstchain
Version: 0.6.3.post354+gitb7d140f
Name: tables
Version: 3.6.1
Name: numpy
Version: 1.20.1

Example of affected file:
- input: `/fefs/aswg/data/mc/DL0/20200629_prod5_trans_80/gamma-diffuse/zenith_20deg/south_pointing/gamma_20deg_180deg_run90___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono_cone6.simtel.gz`
- output: `/fefs/aswg/workspace/mykhailo.dalchenko/tmp/test/output/dl1_gamma_20deg_180deg_run90___cta-prod5-lapalma_4LSTs_MAGIC_desert-2158m_mono_cone6.h5`

**Comment by maxnoe** [comment]
Can you provide the command you ran?

**Comment by maxnoe** [comment]
It would be great if you could contribute such fixes to the code.

**Comment by mexanick** [comment]
Well, I was about to submit a PR, but stuck with this very issue 😊

**Comment by rlopezcoto** [comment]
@mexanick thanks for sharing. As you could see, at the moment lstchain is going under some heavy coding and things for some versions may not have worked in some of the unreleased versions. 
Since this is MC, in principle it should not be so much affected, but as @maxnoe pointed out, it would be great to have a look to the specific command that you run to be more helpful

**Comment by maxnoe** [comment]
We shouldn't rely on these names at all. There are several issues and bugs related to this, especially to the fact that the two magics differ but have the same name.

Next version of ctapipe will switch to only using tel ids and indexes and not rely on names / guessing descriptions from parameters.

I think most of the scripts in lstchain, especially the ones used for observed rather than  simulated data, only work with pure lst or even only a single telescope.

**Comment by maxnoe** [comment]
Probably the best solution here would be to just calculate the disp parameters also inside the telescope event loop, not all at once afterwards.
