### ISSUE TITLE
Unusable pixels error in dl1ab

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#669]
Got this error while running the `lstchain_dl1ab` script (with pedestal cleaning and tailcut 8-4) for run 02927, sub-run 0164 (out of 245 total sub-runs) from 2020-01-18 using lstchain v0.7.1

Command:
```bash
lstchain_dl1ab \
  --input-file=/fefs/aswg/data/real/running_analysis/20201118/v0.7.1/dl1_LST-1.Run02927.0164.h5 \
  --output-file=/fefs/aswg/data/real/running_analysis/20201118/v0.7.1/tailcut84/dl1_LST-1.Run02927.0164.h5 \
  --pedestal-cleaning=True \
  --config=/fefs/aswg/lstosa/config_files_lstchain/lstchain_standard_config_tailcut84.json
```

```python
Traceback (most recent call last):
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/bin/lstchain_dl1ab", line 8, in <module>
    sys.exit(main())
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/scripts/lstchain_dl1ab.py", line 89, in main
    pedestal_thresh = get_threshold_from_dl1_file(args.input_file, sigma)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/calib/camera/pixel_threshold_estimation.py", line 65, in get_threshold_from_dl1_file
    unusable_pixels = get_unusable_pixels(dl1_path, interleaved_events_id)
  File "/fefs/aswg/software/virtual_env/anaconda3/envs/osa/lib/python3.7/site-packages/lstchain/calib/camera/pixel_threshold_estimation.py", line 76, in get_unusable_pixels
    HIGH_GAIN,
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by maxnoe** [comment]
It seems the shape of `unusable_pixels` does not match the shape of `ped_std_pe`

**Comment by morcuended** [comment]
Thanks for the inspection @maxnoe. @pawel21, @rlopezcoto, @moralejo can this be fixed? From the hardware/observation point of view what changes in order to produce these different shapes? Is that sometimes you cannot identify properly interleaved pedestal events?

**Comment by maxnoe** [comment]
For the file that raises the error:
```
In [13]: f.root[dl1_params_tel_mon_cal_key].col("unusable_pixels").shape
Out[13]: (1, 2, 1855)
```

For another file:
```
In [16]: f.root[dl1_params_tel_mon_cal_key].col("unusable_pixels").shape
Out[16]: (2, 2, 1855)
```

**Comment by rlopezcoto** [comment]
it seems that there was a check introduced by @pawel21 in case there were problems with interleaved pedestal std values:
https://github.com/cta-observatory/cta-lstchain/blob/c741c9d89ffe20f3a47d5c3f7addf582f26b95b2/lstchain/calib/camera/pixel_threshold_estimation.py#L55-L57

but as @maxnoe pointed out, it seems that the shape of `unusable_pixels` and `ped_std_pe` did not match. @pawel21 could you please check this? Thanks

**Comment by moralejo** [comment]
Perhaps the additional dimension is omitted if all pixels are usable for one of the gains?

**Comment by pawel21** [comment]
> but as @maxnoe pointed out, it seems that the shape of `unusable_pixels` and `ped_std_pe` did not match. @pawel21 could you please check this? Thanks
 Yes, I will check it.

**Comment by moralejo** [comment]
https://github.com/cta-observatory/cta-lstchain/blob/44331a084875e05e5fba598a8beac762d5d93fbb/lstchain/calib/camera/pixel_threshold_estimation.py#L55-L61

This does not look correct to me. If no pedestal monitoring info from subrun is available (why would that be the case?) then the info from the calib run (possibly taken way earlier, with stars in different positions) is taken.

**Comment by moralejo** [comment]
https://github.com/cta-observatory/cta-lstchain/blob/c01715eaea88aa7cb35a129a0d7dbc7347644655/lstchain/reco/r0_to_dl1.py#L333-L340

@FrancaCassol may the recent change here (the deepcopy) be related? Perhaps the info from the interleaved events is not placed where dl1ab expects it?

**Comment by moralejo** [comment]
The problem is the inconsistency between the shapes of 
dl1.event.telescope.monitoring.pedestal.col('charge_std')
and
dl1.event.telescope.monitoring.calibration.col('unusable_pixels')

The former is used to decide what element of the latter (in the first dimension) has to be taken.
But unusable pixels comes not just from the pedestal events, but also from flatfield events. If there was some problem with interleaved ff events, and the unusable pixels was not updated (i.e. the entry [1] created and filled), that will fail.

**Comment by moralejo** [comment]
https://github.com/cta-observatory/cta-lstchain/blob/c01715eaea88aa7cb35a129a0d7dbc7347644655/lstchain/reco/r0_to_dl1.py#L346-L354

"if new_ped_event **or** new_ff_event: "  is what makes that you can have inconsistent dimensions between the FF and pedestal monitoring which ultimately create the problem. But of course, if you have only interleaved events of one type you should keep them, so the solution should probably go in dl1ab, upon deciding what to do with the unusable pixels and the charge_std arrays...

**Comment by moralejo** [comment]
I think I understood it @pawel21 , you have to use e.g. 
dl1.event.telescope.monitoring.pedestal.col('calibration_id')  to get the index from which you have to read the unusable pixels.

So you read the pedestal std from index 1 if it exists, but you don't read the unusable pixels from the same index, but from dl1.event.telescope.monitoring.pedestal.col('calibration_id')[1]

Perhaps @FrancaCassol can confirm this

**Comment by moralejo** [comment]
https://github.com/cta-observatory/cta-lstchain/blob/44331a084875e05e5fba598a8beac762d5d93fbb/lstchain/calib/camera/pixel_threshold_estimation.py#L74-L77

I mean to replace above interleaved_events_id by dl1.event.telescope.monitoring.pedestal.col('calibration_id')[interleaved_events_id]

**Comment by FrancaCassol** [comment]
Hi @moralejo, @pawel21,

> I think I understood it @pawel21 , you have to use e.g.
> dl1.event.telescope.monitoring.pedestal.col('calibration_id') to get the index from which you have to read the unusable pixels.

I confirm.

**Comment by pawel21** [comment]
> Hi @moralejo, @pawel21,
> 
> > I think I understood it @pawel21 , you have to use e.g.
> > dl1.event.telescope.monitoring.pedestal.col('calibration_id') to get the index from which you have to read the unusable pixels.
> 
> I confirm.

Thank you, I will fix it.

**Comment by morcuended** [comment]
I confirm that these errors do not happen anymore with the current master version. However, the ones reported in #676 do still happen.
