### ISSUE TITLE
No pedestals found in last subrun of Run07409

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/cta-lstchain#941]
No problems were reported in the ELOG

```
lstchain_dl1ab --input-file=/fefs/aswg/data/real/running_analysis/20220311/v0.9/dl1_LST-1.Run07409.0038.h5 \
 --output-file=/fefs/aswg/data/real/running_analysis/20220311/v0.9/tailcut84/dl1_LST-1.Run07409.0038.h5 \
 --config=/fefs/aswg/lstosa/config_files_lstchain/lstchain_config_v0.9.4_from2022onwards.json
```

```
 Pedestal cleaning
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/osa-v0.9.4/lib/python3.8/site-packages/tables/group.py", line 420, in __getitem__
    return self._f_get_child(childname)
  File "/fefs/aswg/software/conda/envs/osa-v0.9.4/lib/python3.8/site-packages/tables/group.py", line 682, in _f_get_child
    self._g_check_has_child(childname)
  File "/fefs/aswg/software/conda/envs/osa-v0.9.4/lib/python3.8/site-packages/tables/group.py", line 375, in _g_check_has_child
    raise NoSuchNodeError(
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/dl1/event/telescope/monitoring/pedestal``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/osa-v0.9.4/bin/lstchain_dl1ab", line 8, in <module>
    sys.exit(main())
  File "/fefs/aswg/software/conda/envs/osa-v0.9.4/lib/python3.8/site-packages/lstchain/scripts/lstchain_dl1ab.py", line 133, in main
    pedestal_thresh = get_threshold_from_dl1_file(args.input_file, sigma)
  File "/fefs/aswg/software/conda/envs/osa-v0.9.4/lib/python3.8/site-packages/lstchain/calib/camera/pixel_threshold_estimation.py", line 59, in get_threshold_from_dl1_file
    ped_mean_pe, ped_std_pe = get_bias_and_std(dl1_path)
  File "/fefs/aswg/software/conda/envs/osa-v0.9.4/lib/python3.8/site-packages/lstchain/calib/camera/pixel_threshold_estimation.py", line 26, in get_bias_and_std
    ped = f.root[dl1_params_tel_mon_ped_key]
  File "/fefs/aswg/software/conda/envs/osa-v0.9.4/lib/python3.8/site-packages/tables/group.py", line 422, in __getitem__
    raise IndexError(childname)
IndexError: /dl1/event/telescope/monitoring/pedestal
```

**Comment by morcuended** [comment]
The same problem occured for Run07916.0048 (the last subrun of this run) for the record. I discard it from the data processing.
