### ISSUE TITLE
lstchain_dl1ab returns ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by mireianievas** [cta-observatory/cta-lstchain#956]
Running in lst-cp:

```
lstchain_dl1ab -f /fefs/aswg/data/mc/DL1/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/20220303_v0.9.3_prod5_trans_80_zen20az180_dl1ab_tuned_psf/off0.4deg/dl1_gamma_20deg_180deg_off0.4deg_20220303_v0.9.3_prod5_trans_80_zen20az180_dl1ab_tuned_psf_training.h5 -o /fefs/aswg/workspace/mireia.nievas/analysis/MC/dl1ab/20200629_prod5_trans_80/gamma/zenith_20deg/south_pointing/20220303_v0.9.3_prod5_trans_80_zen20az180_dl1ab_tuned_psf/off0.4deg//dl1_gamma_20deg_180deg_off0.4deg_20220303_v0.9.3_prod5_trans_80_zen20az180_dl1ab_tuned_psf_training.h5 -c /fefs/aswg/data/models//20200629_prod5_trans_80/zenith_20deg/south_pointing/20220303_v0.9.3_prod5_trans_80_zen20az180_dl1ab_tuned_psf/lstchain_config.json
```
Returns:

```
Remove from image pixels which have charge below = 0.03 * average size
Traceback (most recent call last):
  File "/home/mireia.nievas/workspace/software/miniconda/envs/lst-dev/bin/lstchain_dl1ab", line 8, in <module>
    sys.exit(main())
  File "/home/mireia.nievas/workspace/software/miniconda/envs/lst-dev/lib/python3.7/site-packages/lstchain/scripts/lstchain_dl1ab.py", line 201, in main
    nodes_keys.remove(dl1_images_lstcam_key)
ValueError: list.remove(x): x not in list
```

I guess that line 201 in lstchain/scripts/lstchain_dl1ab.py should be changed from:

```
if args.no_image:
```

to something like 

```
if args.no_image and dl1_images_lstcam_key in nodes_keys:
```

**Comment by maxnoe** [comment]
@mireianievas You are running `lstchain_dl1ab` on a file that does not contain images. That's not possible. The error could be better though

**Comment by mireianievas** [comment]
Ok, thanks !

Besides, I think I was mixing somehow an older version of lstchain ...
